name: church_of_christ
description: application for Acapella music

version: 3.0.0+15

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Network 
  dio: ^3.0.1
  http: ^0.12.2

  #core  
  shared_preferences: ^0.5.8
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  localstorage: ^3.0.3+6
  provider: ^4.3.2+3
  path_provider: ^1.6.24

  #Online
  flutter_web_browser: ^0.12.0
  flutter_mailer: ^1.0.1

  #Icons
  cupertino_icons: ^0.1.3
  typicons_flutter: ^0.3.1
  flutter_vector_icons: ^0.2.1  

  #Audio
  audioplayers: ^0.17.0

  #Images
  cached_network_image: ^2.2.0+1

  #Widgets
  row_collection: ^0.2.5
  flutter_markdown: ^0.4.4

  #UI
  shimmer: ^1.1.2
  bubble_bottom_bar: ^1.2.0
  pull_to_refresh: 1.6.3
  toast: ^0.1.5
  empty_widget: ^0.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/acamusic.png"

flutter:

  uses-material-design: true

  #assets:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  assets:
    - assets/icons/
    - assets/images/
