name: church_of_christ
description: application for Acapella music

version: 3.2.0+38

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Network 
  dio: ^4.0.0
  http: ^0.13.2

  #Firebase


  #core  
  shared_preferences: ^2.0.5
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  localstorage: ^4.0.0+1
  provider: ^4.3.2+3
  path_provider: ^2.0.1
  permission_handler: ^6.1.3
  
  #Firebase
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+4
  firebase_auth: ^1.4.1
  google_sign_in: ^4.4.4


  #Online
  flutter_web_browser: ^0.15.0
  flutter_mailer: ^1.0.1
  flutter_share: ^2.0.0


  #Icons
  cupertino_icons: ^0.1.3
  #typicons_flutter: ^0.3.1
  #flutter_vector_icons: ^0.2.1  

  #Audio
  #audioplayers: ^0.18.3
  assets_audio_player: ^3.0.3+6
  #just_audio: ^0.7.4
  #audio_service: ^0.17.0

  #Images
  cached_network_image: ^3.0.0

  #Widgets
  row_collection: ^0.2.5
  flutter_markdown: ^0.6.1
  marquee: ^2.1.0


  #UI
  shimmer: ^1.1.2
  bubble_bottom_bar: ^1.2.0
  pull_to_refresh: ^1.6.5
  toast: ^0.1.5
  after_layout: ^1.0.7+2  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/acamusic.png"

flutter:

  uses-material-design: true

  #assets:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  assets:
    - assets/icons/
    - assets/images/
